category_app/urls.py
from django.urls import path
from . import views

app_name = 'category_app'

urlpatterns = [
    path('category/<int:pk>', views.category, name='category'),
    path('artists', views.song, name='artists'),
    path('artist/<int:pk>', views.artist, name='artist'),
    path('album/<int:pk>', views.album, name='album'),
    path('base/<int:pk>', views.base, name='cat'),
    path('search', views.search, name='search'),
    
]

home_app/urls.py
from django.urls import path
from . import views


app_name = 'home_app'


urlpatterns = [
    path('', views.home, name='home'),
]

music_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_app.urls')),
    path('', include('category_app.urls')),
]+static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

category_app/models.py
from django.db import models

# Create your models here.


class Category(models.Model):
    tittle = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.tittle


class Artist(models.Model):
    name = models.CharField(max_length=100, null=True)
    image = models.ImageField(upload_to='artist_image')
    category = models.ManyToManyField(Category, related_name='artists')

    def __str__(self):
        return self.name


class Album(models.Model):
    name = models.CharField(max_length=100, null=True)
    image = models.ImageField(upload_to='album_image')
    release_date = models.IntegerField(null=True)
    artist = models.ManyToManyField(Artist, related_name='albums')

    def __str__(self):
        return self.name


class Song(models.Model):
    name = models.CharField(max_length=100, null=True)
    song = models.FileField(upload_to='songs', null=True, blank=True)
    image = models.ImageField(upload_to='images')
    artist_name = models.CharField(max_length=100, null=True)
    artist = models.ManyToManyField(Artist, related_name='songs')
    category = models.ManyToManyField(Category, related_name='songs')
    release_date = models.IntegerField(null=True)
    album = models.ManyToManyField(Album, related_name='songs')
    album_name = models.CharField(max_length=100, null=True)

    def __str__(self):
        return self.name

    

home_app/models.py
from django.db import models

# Create your models here.

category_app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Song, Artist, Category, Album
from django.core.paginator import Paginator

def song(request):
    categories = Category.objects.all()
    artists = Artist.objects.all()
    songs = Song.objects.all()
    page_number = request.GET.get('page')
    paginator = Paginator(artists, 3)
    artists_list = paginator.get_page(page_number)
    return render(request, 'artists.html', context={'songs': songs, 'artists': artists_list, 'cats': categories})

def artist(request, pk=None):
    categories = Category.objects.all()
    artist = Artist.objects.get(id=pk)
    albums = artist.albums.all()
    songs = artist.songs.all()
    return render(request, 'cat2.html', context={'songs': songs, 'artist': artist, 'cats': categories, 'albums':albums})

def category(request, pk=None):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=pk)
    artists = category.artists.all()
    page_number = request.GET.get('page')
    paginator = Paginator(artists, 3)
    artists_list = paginator.get_page(page_number)
    songs = category.songs.all()
    return render(request, 'artists.html', context={'songs': songs, 'artists': artists_list, 'cats': categories})

def album(request, pk=None):
    categories = Category.objects.all()
    album = Album.objects.get(id=pk)
    artist = album.artist.all()
    songs = album.songs.all()
    return render(request, 'cat3.html', context={'songs': songs, 'artist': artist, 'cats': categories, 'album':album})


def base(request):
    categories = Category.objects.all()
    return render(request, 'base.html', context={'cats':categories})

def search(request):
    q = request.GET.get('q')
    artists_list = Artist.objects.filter(name__icontains=q)
    return render(request, 'artists.html', context={'artists': artists_list})
 

home_app/views.py
from django.shortcuts import render

# Create your views here.


def home(request):
    return render(request, "index.html")

templates/artists.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Category section -->
<section class="category-section spad">
	<div class="container-fluid">
		<div class="section-title">
			<h2>Artists</h2>
		</div>
		<div class="container">
			<div class="category-links">
				<a href="{% url 'category_app:artists' %}">All Artists</a>
				{% for cat in cats %}
					<a href="{% url 'category_app:category' cat.id %}">{{ cat.tittle }}</a>
				{% endfor %}
			</div>
		</div>

	<section class="help-section spad pt-0">
		<div class="container">
			<div class="row">
				<div class="col-lg-6">
					<div class="section-title mb-0 pb-4">
						<h3>Need Help to find music? </h3>
					</div>
{#					<p>Consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Risus commodo viverra maecenas accumsan lacus vel facilisis. </p>#}
				</div>
				<div class="col-lg-6">
					<div class="d-flex h-100 align-items-end">
						<form class="search-form" method="GET" action="{% url 'category_app:search' %}">
							<input type="text" name="q" placeholder="Hit it">
							<button>Search</button>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
		<div class="category-items">
			<div class="row">
				{% for artist in artists %}
					<div class="col-md-4">
						<div class="category-item">
							<img src="{{artist.image.url }}" alt="">
							<div class="ci-text">
								<h4>{{artist.name}}</h4>
								{% comment %} <p>Live from Madrid</p> {% endcomment %}
							</div>
							<a href="{% url 'category_app:artist' artist.id %}" class="ci-link"><i class="fa fa-play"></i></a>
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
</section>
<!-- Category section end -->


<!-- Songs section  -->
<section class="songs-section">
	<div class="container">
		<!-- song -->
		{% comment %} {% for song in songs %}
			<div class="song-item">
				<div class="row">
					<div class="col-lg-4">
						<div class="song-info-box">
							<img src="{{ song.image.url }}" alt="">
							<div class="song-info">
								<h4>{{ song.name }}</h4>
								<p>{{ song.artist_name  }}</p>
							</div>
						</div>
					</div>
					<div class="col-lg-6">
						<div class="single_player_container">
							<div class="single_player">
								<div class="jp-jplayer jplayer" id="jplayer_{{ forloop.counter }}" data-ancestor=".jp_container_{{ forloop.counter }}" data-url="{{song.song.url}}"></div>
								<div class="jp-audio jp_container_{{ forloop.counter }}" role="application" aria-label="media player">
									<div class="jp-gui jp-interface">

										<!-- Player Controls -->
										<div class="player_controls_box">
											<button class="jp-prev player_button" tabindex="0"></button>
											<button class="jp-play player_button" tabindex="0"></button>
											<button class="jp-next player_button" tabindex="0"></button>
											<button class="jp-stop player_button" tabindex="0"></button>
										</div>
										<!-- Progress Bar -->
										<div class="player_bars">
											<div class="jp-progress">
												<div class="jp-seek-bar">
													<div>
														<div class="jp-play-bar"><div class="jp-current-time" role="timer" aria-label="time">0:00</div></div>
													</div>
												</div>
											</div>
											<div class="jp-duration ml-auto" role="timer" aria-label="duration">00:00</div>
										</div>
									</div>
									<div class="jp-no-solution">
										<span>Update Required</span>
										To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-2">
						<div class="songs-links">
							<a href=""><img src="{% static 'img/icons/p-1.png' %}" alt=""></a>
							<a href="{{song.song.url}}" download ><img src="{% static 'img/icons/p-2.png' %}" alt="Download"></a>
							<a href=""><img src="{% static 'img/icons/p-3.png' %}" alt=""></a>
						</div>
					</div>               
				</div>
			</div>
		{% endfor %} {% endcomment %}
		<div class="pagination">
            {% for i in artists.paginator.page_range %}
			    {% if artists.number == i %}
                     <a href="?page= {{ i }}" class="active">{{ i }}</a>
                {% else %}
                    <a href="?page= {{ i }}">{{ i }}</a>
                {% endif %}
            {% endfor %}
		</div>
	</div>
</section>
<!-- Songs section end -->

{% endblock %}

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>SolMusic | HTML Template</title>
	<meta charset="UTF-8">
	<meta name="description" content="SolMusic HTML Template">
	<meta name="keywords" content="music, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	
	<!-- Favicon -->
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google font -->
	<link href="{% static 'https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i,600,600i,700,700i&display=swap' %}" rel="stylesheet">
 
	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}"/>

	<!-- Main Stylesheets -->
	<link rel="stylesheet" href="{% static "css/style.css" %}"/>

	<script src="{https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="{https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<script src="{https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <!-- jPlayer -->
    <script src="{https://cdnjs.cloudflare.com/ajax/libs/jplayer/2.9.2/jplayer/jquery.jplayer.min.js"></script>


	<script src="{https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="{% static 'path/to/jplayer/jquery.jplayer.min.js' %}"></script>
	<script src="{https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="{https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	


</head>
<body>
	<!-- Page Preloder -->
	{% comment %} <div id="preloder">
		<div class="loader"></div>
	</div> {% endcomment %}

	<!-- Header section -->
	<header class="header-section clearfix">
		<a href="index.html" class="site-logo">
			<img src="{% static 'img/logo.png' %}" alt="">
		</a>
		<div class="header-right">
{#			<a href="#" class="hr-btn">Help</a>#}
{#			<span>|</span>#}
			<div class="user-panel">
				<a href="" class="login">Login</a>
				<a href="" class="register">Create an account</a>
			</div> 
		</div>
		<ul class="main-menu">
			<li><a href="{% url 'home_app:home' %}">Home</a></li>
			<li><a href="{% url 'category_app:artists'%}">Artists</a></li>
			<li><a href="#">Categories</a>
				<ul class="sub-menu">
					{% for cat in cats %}
                        <li><a href="{% url 'category_app:category' cat.id %}">{{ cat.tittle }}</a></li>
                    {% endfor %}
				</ul>
			</li>
{#			<li><a href="blog.html">News</a></li>#}
			<li><a href="contact.html">Contact</a></li>
		</ul>
	</header>



    {% block content %}

    {% endblock %}




    <footer class="footer-section">
		<div class="container">
			<div class="row">
				<div class="col-xl-6 col-lg-7 order-lg-2">
					<div class="row">
						<div class="col-sm-4">
							<div class="footer-widget">
								<h2>About us</h2>
								<ul>
									<li><a href="">Our Story</a></li>
									<li><a href="">Sol Music Blog</a></li>
									<li><a href="">History</a></li>
								</ul>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="footer-widget">
								<h2>Products</h2>
								<ul>
									<li><a href="">Music</a></li>
									<li><a href="">Subscription</a></li>
									<li><a href="">Custom Music</a></li>
									<li><a href="">Footage</a></li>
								</ul>
							</div>
						</div>
						<div class="col-sm-4">
							<div class="footer-widget">
								<h2>Playlists</h2>
								<ul>
									<li><a href="">Newsletter</a></li>
									<li><a href="">Careers</a></li>
									<li><a href="">Press</a></li>
									<li><a href="">Contact</a></li>
								</ul>
							</div>
						</div>
					</div>
				</div>
				<div class="col-xl-6 col-lg-5 order-lg-1">
					<img src="img/logo.png" alt="">
					<div class="copyright"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></div>
					<div class="social-links">
						<a href=""><i class="fa fa-instagram"></i></a>
						<a href=""><i class="fa fa-pinterest"></i></a>
						<a href=""><i class="fa fa-facebook"></i></a>
						<a href=""><i class="fa fa-twitter"></i></a>
						<a href=""><i class="fa fa-youtube"></i></a>
					</div>
				</div>
			</div>
		</div>
	</footer>
	<!-- Footer section end -->
	
	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/jquery.slicknav.min.js' %}"></script>
	<script src="{% static 'js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'js/mixitup.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/jquery.jplayer.min.js' %}"></script>
	<script src="{% static 'js/jplayerInit.js' %}"></script>

	</body>
</html>

templates/blog.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Blog section -->
<section class="blog-section spad">
	<div class="container">
		<!-- Blog post -->
		<div class="blog-item">
			<img src="img/blog/1.jpg" alt="">
			<div class="blog-date">April 14, 2019</div>
			<h3>Top 10 best songs in April</h3>
			<div class="blog-meta">by <a href="">Alan Smith</a> in <a href="">Music</a></div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
		</div>
		<!-- Blog post -->
		<div class="blog-item">
			<img src="img/blog/2.jpg" alt="">
			<div class="blog-date">April 14, 2019</div>
			<h3>Summer Festivals that you cannot miss</h3>
			<div class="blog-meta">by <a href="">Alan Smith</a> in <a href="">Music</a></div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
		</div>
		<!-- Blog post -->
		<div class="blog-item">
			<img src="img/blog/3.jpg" alt="">
			<div class="blog-date">April 14, 2019</div>
			<h3>Michael Smith latest album is out now</h3>
			<div class="blog-meta">by <a href="">Alan Smith</a> in <a href="">Music</a></div>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
		</div>
		<div class="site-pagination">
			<a href="#" class="active">01.</a>
			<a href="#">02.</a>
			<a href="#">03.</a>
			<a href="#">04.</a>
		</div>
	</div>
</section>
<!-- Blog section end -->


{% endblock %}

templates/cat2.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Category section -->
<section class="category-section spad">
	<div class="container-fluid">
		<div class="section-title">
			<h2>{{ artist.name }}</h2>
		</div>
		<div class="container">
			<div class="category-links">
				<a href="{% url 'category_app:artists' %}">All Artists</a>
				{% for cat in cats %}
					<a href="{% url 'category_app:category' cat.id %}">{{ cat.tittle }}</a>
				{% endfor %}
			</div>
		</div>
		<div class="category-items">
			<div class="row">
					<div class="col-md-4">
						<div class="category-item">
							<img src="{{artist.image.url }}" alt="">
							<div class="ci-text">
								<h4>{{artist.name}}</h4>
								{% comment %} <p>Live from Madrid</p> {% endcomment %}
							</div>
							<a href="{% url 'category_app:artist' artist.id %}" class="ci-link"><i class="fa fa-play"></i></a>
						</div>
					</div>
			</div>
		</div>
        <div class="category-items">
			<div class="row">
				{% for album in albums %}
					<div class="col-md-4">
						<div class="category-item2">
							<a href="{% url 'category_app:album' album.id %}" ><img src="{{ album.image.url }}" alt=""></a>
							<div class="ci-text2">
{#								<h4>{{artist.name}}</h4>#}
								{% comment %} <p>Live from Madrid</p> {% endcomment %}
							</div>
{#							<a href="{% url 'category_app:album' album.id %}" class="ci-link"><i class="fa fa-play"></i></a>#}
						</div>
					</div>
				{% endfor %}
			</div>
		</div>
	</div>
</section>
<!-- Category section end -->

<!-- Songs section  -->
<section class="songs-section">
	<div class="container">
{#		<!-- song -->#}
{#		{% for song in songs %}#}
{#			<div class="song-item">#}
{#				<div class="row">#}
{#					<div class="col-lg-4">#}
{#						<div class="song-info-box">#}
{#							<img src="{{ song.image.url }}" alt="">#}
{#							<div class="song-info" style="display: inline">#}
{#								<h4>{{ song.name }}</h4>#}
{#								<p>{{ song.artist_name  }}</p>#}
{#                                <p>{{ song.album_name }}</p>#}
{#                                <p>{{ song.release_date }}</p>#}
{#							</div>#}
{#					</div>#}
{#					</div>#}
{#					<div class="col-lg-6">#}
{#						<div class="single_player_container">#}
{#							<div class="single_player">#}
{#								<div class="jp-jplayer jplayer" id="jplayer_{{ forloop.counter }}" data-ancestor=".jp_container_{{ forloop.counter }}" data-url="{{song.song.url}}"></div>#}
{#								<div class="jp-audio jp_container_{{ forloop.counter }}" role="application" aria-label="media player">#}
{#									<div class="jp-gui jp-interface">#}
{##}
{#										<!-- Player Controls -->#}
{#										<div class="player_controls_box">#}
{#											<button class="jp-prev player_button" tabindex="0"></button>#}
{#											<button class="jp-play player_button" tabindex="0"></button>#}
{#											<button class="jp-next player_button" tabindex="0"></button>#}
{#											<button class="jp-stop player_button" tabindex="0"></button>#}
{#										</div>#}
{#								<!-- Progress Bar -->#}
{#										<div class="player_bars">#}
{#											<div class="jp-progress">#}
{#												<div class="jp-seek-bar">#}
{#													<div>#}
{#														<div class="jp-play-bar"><div class="jp-current-time" role="timer" aria-label="time">0:00</div></div>#}
{#													</div>#}
{#												</div>#}
{#											</div>#}
{#											<div class="jp-duration ml-auto" role="timer" aria-label="duration">00:00</div>#}
{#										</div>#}
{#									</div>#}
{#									<div class="jp-no-solution">#}
{#										<span>Update Required</span>#}
{#										To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>#}
{#									</div>#}
{#								</div>#}
{#							</div>#}
{#						</div>#}
{#					</div>#}
{#					<div class="col-lg-2">#}
{#						<div class="songs-links">#}
{#							<a href=""><img src="{% static 'img/icons/p-1.png' %}" alt=""></a>#}
{#							<a href="{{song.song.url}}" download ><img src="{% static 'img/icons/p-2.png' %}" alt="Download"></a>#}
{#							<a href=""><img src="{% static 'img/icons/p-3.png' %}" alt=""></a>#}
{#						</div>#}
{#					</div>               #}
{#				</div>#}
{#			</div>#}
{#		{% endfor %}#}
{#		<div class="site-pagination pt-5 mt-5">#}
{#			<a href="#" class="active">01.</a>#}
{#			<a href="#">02.</a>		#}
{#			<a href="#">03.</a>#}
{#			<a href="#">04.</a>#}
{#		</div>#}
{#	</div>#}
</section>
<!-- Songs section end -->

{% endblock %}

templates/cat3.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Category section -->
<section class="category-section spad">
	<div class="container-fluid">
		<div class="section-title">
			<h2>{{ album.name }}</h2>
            <h5>{{ artist.get.name }}</h5>
		</div>
		<div class="container">
			<div class="category-links">
				<a href="{% url 'category_app:artists' %}">All Artists</a>
				{% for cat in cats %}
					<a href="{% url 'category_app:category' cat.id %}">{{ cat.tittle }}</a>
				{% endfor %}
			</div>
		</div>
		<div class="category-items">
			<div class="row">
					<div class="col-md-4">
						<div class="category-item2">
							<img src="{{album.image.url }}" alt="">
							<div class="ci-text">
								<h4>{{album.name}}</h4>
								{% comment %} <p>Live from Madrid</p> {% endcomment %}
							</div>
{#							<a href="{% url 'category_app:artist' artist.id %}" class="ci-link"><i class="fa fa-play"></i></a>#}
						</div>
					</div>
			</div>
		</div>
{#        <div class="category-items">#}
{#			<div class="row">#}
{#				{% for album in albums %}#}
{#					<div class="col-md-4">#}
{#						<div class="category-item2">#}
{#							<img src="{{ album.image.url }}" alt="">#}
{#							<div class="ci-text">#}
{#								<h4>{{artist.name}}</h4>#}
{#								{% comment %} <p>Live from Madrid</p> {% endcomment %}#}
{#							</div>#}
{#							<a href="{% url 'category_app:artist' artist.id %}" class="ci-link"><i class="fa fa-play"></i></a>#}
{#						</div>#}
{#					</div>#}
{#				{% endfor %}#}
{#			</div>#}
		</div>
	</div>
</section>
<!-- Category section end -->

<!-- Songs section  -->
<section class="songs-section">
	<div class="container">
		<!-- song -->
		{% for song in songs %}
			<div class="song-item">
				<div class="row">
					<div class="col-lg-4">
						<div class="song-info-box">
							<img src="{{ song.image.url }}" alt="">
							<div class="song-info" style="display: inline">
								<h4>{{ song.name }}</h4>
								<p>{{ song.artist_name  }}</p>
                                <p>{{ song.album_name }}</p>
                                <p>{{ song.release_date }}</p>
							</div>
					</div>
					</div>
					<div class="col-lg-6">
						<div class="single_player_container">
							<div class="single_player">
								<div class="jp-jplayer jplayer" id="jplayer_{{ forloop.counter }}" data-ancestor=".jp_container_{{ forloop.counter }}" data-url="{{song.song.url}}"></div>
								<div class="jp-audio jp_container_{{ forloop.counter }}" role="application" aria-label="media player">
									<div class="jp-gui jp-interface">

										<!-- Player Controls -->
										<div class="player_controls_box">
											<button class="jp-prev player_button" tabindex="0"></button>
											<button class="jp-play player_button" tabindex="0"></button>
											<button class="jp-next player_button" tabindex="0"></button>
											<button class="jp-stop player_button" tabindex="0"></button>
										</div>
								<!-- Progress Bar -->
										<div class="player_bars">
											<div class="jp-progress">
												<div class="jp-seek-bar">
													<div>
														<div class="jp-play-bar"><div class="jp-current-time" role="timer" aria-label="time">0:00</div></div>
													</div>
												</div>
											</div>
											<div class="jp-duration ml-auto" role="timer" aria-label="duration">00:00</div>
										</div>
									</div>
									<div class="jp-no-solution">
										<span>Update Required</span>
										To play the media you will need to either update your browser to a recent version or update your <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-2">
						<div class="songs-links">
							<a href=""><img src="{% static 'img/icons/p-1.png' %}" alt=""></a>
							<a href="{{song.song.url}}" download ><img src="{% static 'img/icons/p-2.png' %}" alt="Download"></a>
							<a href=""><img src="{% static 'img/icons/p-3.png' %}" alt=""></a>
						</div>
					</div>               
				</div>
			</div>
		{% endfor %}
{#		<div class="site-pagination pt-5 mt-5">#}
{#			<a href="#" class="active">01.</a>#}
{#			<a href="#">02.</a>		#}
{#			<a href="#">03.</a>#}
{#			<a href="#">04.</a>#}
{#		</div>#}
{#	</div>#}
</section>
<!-- Songs section end -->

{% endblock %}

templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

	<!-- Contact section -->
	<section class="contact-section">
		<div class="container-fluid">
			<div class="row">
				<div class="col-lg-6 p-0">
					<!-- Map -->
					<div class="map"><iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d10784.188505644011!2d19.053119335158936!3d47.48899529453826!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sen!2sbd!4v1543907528304" style="border:0" allowfullscreen></iframe></div>
				</div>
				<div class="col-lg-6 p-0">
					<div class="contact-warp">
						<div class="section-title mb-0">
							<h2>Get in touch</h2>
						</div>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore mag na aliqua. Quis ipsum suspendisse ultrices gravida. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed doe iusmod tempor incididunt ut labore et dolore magna aliqua. Quis ipsum suspendisse ultrices gravida. </p>
						<ul>
							<li>Main Road , No 25/11</li>
							<li>+34 556788 3221</li>
							<li>contact@solmusic.com</li>
						</ul>
						<form class="contact-from">
							<div class="row">
								<div class="col-md-6">
									<input type="text" placeholder="Your name">
								</div>
								<div class="col-md-6">
									<input type="text" placeholder="Your e-mail">
								</div>
								<div class="col-md-12">
									<input type="text" placeholder="Subject">
									<textarea placeholder="Message"></textarea>
									<button class="site-btn">send message</button>
								</div>
							</div>
						</form>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Blog section end -->



{% endblock %}

templates/main.html
<a href="https://colorlib.com/wp/templates/"><img src="https://colorlib.com/wp/wp-content/uploads/sites/2/colorlib-push-logo.png" alt="Colorlib logo"></a>
<h1 style="text-align:center;">Thank you for using our template!</h1>
<p style="text-align:center;">For more awesome templates please visit <strong><a href="https://colorlib.com/wp/templates/">Colorlib</a></strong>.</p>
<br>
<p style="text-align:center; color:red;"><strong>Copyright information for the template can't be altered/removed unless you purchase a license.</strong>

<p style="text-align:center;"><strong>Removing copyright information without the license will result in suspension of your hosting and/or domain name(s).</strong>

<p style="text-align:center;"><strong>More information about the license is available <a href="https://colorlib.com/wp/licence/">here</a></strong>.</p>

<style>
img {
  margin: 0 auto;
  display: block;
  margin-top: 20%;
}
</style>